server:
  port: 8762

spring:
  application:
    name: mini-weather-api-server
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/miniprogram?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#整合Mybatis
mybatis:
  #  扫描数据持久对应的实体类 路径 Package级别
  type-aliases-package: com.chris.mini.weather.api.bean
  #  mybatis 对应的 .xml文件路径
  mapper-locations: classpath:mapper/*.xml
#  多层级目录  mapper-locations: classpath:mapper/**/**.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



